name: 'Build my corne'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y", CONFIG_ZMK_RGB_UNDERGLOW=n, CONFIG_WS2812_STRIP=n, CONFIG_ZMK_SLEEP=y ]'
      alphas: '["qwertz"]'
      clipboard: '["win"]'
